source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'

pod 'BButton'
pod "AFNetworking", "~> 2.0"
pod 'CTCheckbox', '~> 0.0.3'
pod 'Parse', '~> 1.7.3'
pod 'RNActivityView'
pod 'TDSemiModal'
pod 'ParseUI', '~> 1.1.3'